### ISSUE TITLE
Request: Escape string fields expected to contain freeform user input

### ISSUE THREAD

**Issue by jkotanchik-SB** [cqframework/sample-content-ig#10]
Fields that contain user supplied input may contain characters not supported by the parser. Where possible, use the [FHIRPath escape function](https://build.fhir.org/ig/HL7/FHIRPath/#escapetarget-string-string) to avoid exceptions during parsing.

**Noted areas:**
Measure Description: 
https://github.com/cqframework/sample-content-ig/blob/bca8df99f5361c4829d1065bca67c5e7ab9fed0a/templates/liquid/Measure.liquid#L176

Group Population Descriptions: 
https://github.com/cqframework/sample-content-ig/blob/bca8df99f5361c4829d1065bca67c5e7ab9fed0a/templates/liquid/Measure.liquid#L194
https://github.com/cqframework/sample-content-ig/blob/bca8df99f5361c4829d1065bca67c5e7ab9fed0a/templates/liquid/Measure.liquid#L582

SDE Description & SDE Criteria Descriptions:
https://github.com/cqframework/sample-content-ig/blob/bca8df99f5361c4829d1065bca67c5e7ab9fed0a/templates/liquid/Measure.liquid#L668-L675

RAV Description & RAV Criteria Descriptions:
https://github.com/cqframework/sample-content-ig/blob/bca8df99f5361c4829d1065bca67c5e7ab9fed0a/templates/liquid/Measure.liquid#L691-L699

CQL Statement Extension Values:
https://github.com/cqframework/sample-content-ig/blob/bca8df99f5361c4829d1065bca67c5e7ab9fed0a/templates/liquid/Measure.liquid#L495-L497
https://github.com/cqframework/sample-content-ig/blob/bca8df99f5361c4829d1065bca67c5e7ab9fed0a/templates/liquid/Measure.liquid#L650-L652

**Comment by brynrhodes** [comment]
Closing this issue as not needed, given that the publisher does this processing (and other consumers of liquid template output would be expected to do the same as appropriate for display in their particular environment). Feel free to reopen or submit another issue if needed.
