### ISSUE TITLE
Request: Escape additional string fields that contain freeform user input

### ISSUE THREAD

**Issue by nmorasb** [cqframework/sample-content-ig#11]
Fields that contain user supplied input may contain characters not supported by the parser. Where possible, use the [FHIRPath escape function](https://build.fhir.org/ig/HL7/FHIRPath/#escapetarget-string-string) to avoid exceptions during parsing.

Noted areas:
Measure Purpose:
https://github.com/cqframework/sample-content-ig/blob/bca8df99f5361c4829d1065bca67c5e7ab9fed0a/templates/liquid/Measure.liquid#L250

Measure Usage:
https://github.com/cqframework/sample-content-ig/blob/bca8df99f5361c4829d1065bca67c5e7ab9fed0a/templates/liquid/Measure.liquid#L256

Measure Copyright:
https://github.com/cqframework/sample-content-ig/blob/bca8df99f5361c4829d1065bca67c5e7ab9fed0a/templates/liquid/Measure.liquid#L262

Measure Disclaimer:
https://github.com/cqframework/sample-content-ig/blob/bca8df99f5361c4829d1065bca67c5e7ab9fed0a/templates/liquid/Measure.liquid#L268

**Comment by brynrhodes** [comment]
Closing this issue as not needed, given that the publisher does this processing (and other consumers of liquid template output would be expected to do the same as appropriate for display in their particular environment). Feel free to reopen or submit another issue if needed.
