### ISSUE TITLE
Relabel identifier fields

### ISSUE THREAD

**Issue by juliet-rubini** [cqframework/sample-content-ig#13]
Currently the liquid template human readable output from MADiE looks like this for the identifier fields:
<img width="512" alt="image" src="https://github.com/cqframework/sample-content-ig/assets/113203126/08a4a3f3-5a9f-4cba-b040-39df228ed2c0">

Please update to look like this:
<img width="485" alt="image" src="https://github.com/cqframework/sample-content-ig/assets/113203126/790e0486-dbf4-451f-941e-856b7292b493">

**Comment by echicoine-icf** [comment]
PR here: https://github.com/cqframework/sample-content-ig/pull/18

**Comment by juliet-rubini** [comment]
After the release of MADiE in September using liquid template v0.1.0, the identifier fields still need adjusting.  See attached document 
[Juliet export 9.21.23 after library update.docx](https://github.com/cqframework/sample-content-ig/files/12702878/Juliet.export.9.21.23.after.library.update.docx)
with fields highlighted in yellow.

**Comment by brynrhodes** [comment]
Included in 0.2.0
