### ISSUE TITLE
Reorder the fields in the liquid template

### ISSUE THREAD

**Issue by juliet-rubini** [cqframework/sample-content-ig#14]
Please reorder the fields in the liquid template to match the attached documents.  There is one for each measure type (ratio, proportion, CV). Thanks.
[QDM CV to FHIR human readable mapping.docx](https://github.com/cqframework/sample-content-ig/files/11909447/QDM.CV.to.FHIR.human.readable.mapping.docx)
[QDM proportion to FHIR mapping.docx](https://github.com/cqframework/sample-content-ig/files/11909448/QDM.proportion.to.FHIR.mapping.docx)
[QDM ratio to FHIR human readable mapping.docx](https://github.com/cqframework/sample-content-ig/files/11909449/QDM.ratio.to.FHIR.human.readable.mapping.docx)

**Comment by echicoine-icf** [comment]
PR here: https://github.com/cqframework/sample-content-ig/pull/21

**Comment by juliet-rubini** [comment]
Based on the most recent export from MADiE using v0.1.0 of the liquid template, the following fields appear to be missing:
 Author
measure scoring
measure type
clinical recommendation statement
rationale
endorser
citation
improvement notation

**Comment by brynrhodes** [comment]
Included in 0.3.0
