### ISSUE TITLE
Remove fields from template

### ISSUE THREAD

**Issue by juliet-rubini** [cqframework/sample-content-ig#16]
Based on discussion with measure developers on the 7.6.23 eCQM working group call, please remove the following fields:

Status
Last Review Date
Approval Date

**Comment by brynrhodes** [comment]
Need more discussion on this one, I'm uncomfortable removing these items from the template, they are an important aspect of the measure and should be displayed, yes?

**Comment by juliet-rubini** [comment]
After additional discussion:
Status - make this field conditional - it should only show in the HR when the value is anything other than 'active'
Last Review Date - HIDE
Approval Date - HIDE

**Comment by echicoine-icf** [comment]
PR: https://github.com/cqframework/sample-content-ig/pull/59

**Comment by juliet-rubini** [comment]
Issue addressed in version 0.4.1 and verified via MADiE exports.
