### ISSUE TITLE
Blank fields in logic definitions CQLIT-401

### ISSUE THREAD

**Issue by jenseeman** [cqframework/sample-content-ig#30]
Address blank logic definition fields as reported in https://oncprojectracking.healthit.gov/support/browse/CQLIT-401

**Comment by brynrhodes** [comment]
It's not clear whether this is resolved, the Measure liquid template only contains None, so it's not clear where the Not Applicable is coming from, nor which text should be used "None" or "Not Applicable"

**Comment by brynrhodes** [comment]
Included in 0.2.0
