### ISSUE TITLE
In the Related Artifact Dependencies field, libraries are appearing twice

### ISSUE THREAD

**Issue by juliet-rubini** [cqframework/sample-content-ig#31]
For example, the FHIRHelpers library will show twice

**Comment by juliet-rubini** [comment]
Attaching output from MADiE with related 
[Juliet export 9.21.23 after library update.docx](https://github.com/cqframework/sample-content-ig/files/12729132/Juliet.export.9.21.23.after.library.update.docx)
artifact dependency field highlighted

**Comment by juliet-rubini** [comment]
When reviewing v0.2.0 release examples, it appears this issues is resolved.  will leave this open until we confirm with fresh MADiE exports after implementation of v0.2.0 in MADiE.

**Comment by brynrhodes** [comment]
Included in 0.2.0
