### ISSUE TITLE
Add profiles for the Data Requirements in Human readable

### ISSUE THREAD

**Issue by adongare** [cqframework/sample-content-ig#34]
There are some duplicate Data Requirements seen in the Data requirement section of the Human readable when CQL has both positive and negative profiles. e.g., Observation and ObservationNotDone.

```
Valueset “Standardized Tools Score for Assessment of Cognition”:
definition “x”:
   exists [Observation: “Standardized Tools Score for Assessment of Cognition”]
         or exists [ObservationNotDone: “Standardized Tools Score for Assessment of Cognition”]
```

MADiE is using the Data Requirements Processor to generate the `effectiveDataRequiremets` which will be used later to generate the human readable.  We are using `collapseDataRequirements` translator option to remove duplicates. There are different criteria applied while filtering the duplicates and one of them is profiles. With the above CQL the HR generated will have the following data requirements, note highlighted ones:
![image](https://github.com/cqframework/sample-content-ig/assets/23436747/75bba5f8-fdc0-4217-be9f-6bdba243a868)

Although both data requirements are different, because we do not show profiles, they look exactly the same. Adding the profiles to the data requirements would help users to differentiate them.

**Comment by brynrhodes** [comment]
Included in 0.3.0
