### ISSUE TITLE
Measure Author rendering incorrectly

### ISSUE THREAD

**Issue by nmorasb** [cqframework/sample-content-ig#40]
Measure Author was added to the Measure.liquid template recently, however it doesn't seem to take into account that this is a `List<ContactDetail>` field.
Upon rendering, the Author field looks like this:
![image](https://github.com/cqframework/sample-content-ig/assets/94391996/1e98ecfd-060b-4dea-8f11-1ea3d368039a)

Requesting that this be updated to account for the `List<ContactDetail>`

**Comment by echicoine-icf** [comment]
PR here: https://github.com/cqframework/sample-content-ig/pull/55

**Comment by juliet-rubini** [comment]
Issue addressed in version 0.4.1 and verified via MADiE exports. OK to close tracker!
