### ISSUE TITLE
Make sure all field titles use sentence casing

### ISSUE THREAD

**Issue by juliet-rubini** [cqframework/sample-content-ig#42]
Many of the field names are in lower case.  Please adjust for sentence case to ease readability.  Thanks!

**Comment by echicoine-icf** [comment]
per Bryn: The reason the code displays this way is because it's .display counter-part is not present. To resolve this, a display entry for the identifier is needed.

**Comment by juliet-rubini** [comment]
The displays for the version identifiers are in the value set https://build.fhir.org/ig/HL7/cqf-measures/CodeSystem-identifier-type.html Need to alert the MADiE team to use the display.

**Comment by juliet-rubini** [comment]
MADiE team is tracking this on their side for incorporation via https://oncprojectracking.healthit.gov/support/browse/BONNIEMAT-1729
