### ISSUE TITLE
Restructure Risk Adjustment Variable fields to mirror SDE

### ISSUE THREAD

**Issue by juliet-rubini** [cqframework/sample-content-ig#48]
Instead of having a separate line in the HR for each Risk Adjustment Variable - create one field and use line breaks to separate if more than one is entered.

**Comment by echicoine-icf** [comment]
PR here: https://github.com/cqframework/sample-content-ig/pull/63

**Comment by juliet-rubini** [comment]
This change didn't occur.  In the latest release of MADiE, the Risk adjustment field does not have the same structure as the SDE field when multiple entries are included.  See attached screen shot with highlighted areas for a visual.
[Example_CMS844.docx](https://github.com/cqframework/sample-content-ig/files/14453260/Example_CMS844.docx)

**Comment by juliet-rubini** [comment]
Issue addressed in version 0.4.1 and verified via MADiE exports.
