### ISSUE TITLE
Please reorder the SDE and RAV fields

### ISSUE THREAD

**Issue by juliet-rubini** [cqframework/sample-content-ig#50]
Change the order to:

SDE
SDE Guidance
RAV
RAV guidance

They are currently spread out in the HR in different spots and it doesn't make logical sense.  Thanks.

**Comment by echicoine-icf** [comment]
PR: https://github.com/cqframework/sample-content-ig/pull/61

**Comment by juliet-rubini** [comment]
This change didn't take please.  See attached document highlighting output from MADiE and where the field should move to.
[Example_CMS844.docx](https://github.com/cqframework/sample-content-ig/files/14453274/Example_CMS844.docx)

**Comment by juliet-rubini** [comment]
Issue addressed in version 0.4.1 and verified via MADiE exports.
