### ISSUE TITLE
Remove extra space after first date in the Effective Period field to reduce confusion

### ISSUE THREAD

**Issue by juliet-rubini** [cqframework/sample-content-ig#68]
Currently, the output looks like this:
2025-01-01 ..2025-12-31

Remove extra space after first date so it looks like this:
2025-01-01..2025-12-31

**Comment by echicoine-icf** [comment]
The current entry for this field looks like this:

{{ActivityDefinition.effectivePeriod.start}}..{{ActivityDefinition.effectivePeriod.end}}

There exists certain string functions in liquid template but we don't have access to them with the version we have now. However, in checking the data with Publishable ActivityDefinition Example, I don't see a space:

![image](https://github.com/cqframework/sample-content-ig/assets/81327339/6012e525-9d63-40f1-937f-d550cf9083ad)

So it seems like the space exists within the data itself?

**Comment by echicoine-icf** [comment]
https://github.com/cqframework/sample-content-ig/pull/83

**Comment by juliet-rubini** [comment]
Resolved in version 0.4.3 and released in MADiE 6/206/24
