### ISSUE TITLE
Update formatting for measure scoring 

### ISSUE THREAD

**Issue by juliet-rubini** [cqframework/sample-content-ig#69]
See attached document for the current layout of the logic definitions section and desired changes to make the measure scoring easier to spot.

**Comment by juliet-rubini** [comment]
[Git 69.docx](https://github.com/cqframework/sample-content-ig/files/14703766/Git.69.docx)

**Comment by echicoine-icf** [comment]
PR: https://github.com/cqframework/sample-content-ig/pull/94

**Comment by echicoine-icf** [comment]
![image](https://github.com/cqframework/sample-content-ig/assets/81327339/6d5c0d42-3964-4a79-babf-837a83a140b5)

PR: https://github.com/cqframework/sample-content-ig/pull/96

**Comment by juliet-rubini** [comment]
Resolved in version 0.4.3 and released in MADiE 6/206/24
