### ISSUE TITLE
Measure type field issue

### ISSUE THREAD

**Issue by juliet-rubini** [cqframework/sample-content-ig#71]
The issue with Measure Type is that MADiE is putting out the measure type extension with the following URL: http://hl7.org/fhir/us/cqfmeasures/StructureDefinition/cqfm-type. This URL is correct as per [QMIG STU 4](https://hl7.org/fhir/us/cqfmeasures/StructureDefinition-cqfm-type.html). However, the liquid template is using an incorrect url: http://hl7.org/fhir/us/cqfmeasures/StructureDefinition/cqfm-measureType.
There is also a path issue in the liquid template once one gets by the URL problem. The template is looking for extension.coding as opposed to extension.value.coding

<img width="1043" alt="Screenshot 2024-04-02 153414" src="https://github.com/cqframework/sample-content-ig/assets/113203126/e880c613-0025-461c-b568-f7ad2dbf0bbe">

**Comment by echicoine-icf** [comment]
PR: https://github.com/cqframework/sample-content-ig/pull/84

**Comment by juliet-rubini** [comment]
Resolved in version 0.4.3 and released in MADiE 6/206/24
