### ISSUE TITLE
Improvement notation field fix

### ISSUE THREAD

**Issue by juliet-rubini** [cqframework/sample-content-ig#72]
The issue for improvement notation relates to a path issue. It is looking for extension.coding, which would not exist:
![ImprovementNotation](https://github.com/cqframework/sample-content-ig/assets/113203126/971274d7-b836-4302-8b00-96e2fe25ff7d)

**Comment by echicoine-icf** [comment]
Using extension.value.coding instead

PR: https://github.com/cqframework/sample-content-ig/pull/85

**Comment by juliet-rubini** [comment]
Resolved in version 0.4.3 and released in MADiE 6/20/24
