### ISSUE TITLE
Library.liquid has unsupported Typecasting

### ISSUE THREAD

**Issue by jkotanchik-SB** [cqframework/sample-content-ig#9]
We noticed typecasting the types to CodeableConcept breaks outside of the publisher. FHIRPathEngine is able to recognize it without typecasting, so we can remove the typecasting. 

I believe this change was already done for `Measure.liquid`, and we ask that similar changes be be applied to the useContext section of `Library.liquid`, too.

Noted typecasting:
https://github.com/cqframework/sample-content-ig/blob/bca8df99f5361c4829d1065bca67c5e7ab9fed0a/templates/liquid/Library.liquid#L187-L192

**Comment by brynrhodes** [comment]
Included in 0.3.0
